export enum AwardType {
  ASISTENCIA = "ASISTENCIA",
  VELOCIDAD = "VELOCIDAD",
  RITMO = "RITMO",
  DOWNWIND = "DOWNWIND",
  SPRINTS = "SPRINTS",
  COMBINADAS = "COMBINADAS",
  FUERZAAEREA = "FUERZA AÉREA",
  FUERZA = "FUERZA",
  FUERZATERRESTRE = "FUERZATERRESTRE",
}
