export const teams_DB_DATA = [
  {
    name: "A tope",
    description: "Asiste una semana completa",
    points: 1,
    type: "GENERAL",
    subtype: "ASISTENCIA",
    order: 1,
  },
  {
    name: "Rey del gym",
    description: "Asiste un mes completo al físico",
    points: 1,
    type: "GENERAL",
    subtype: "ASISTENCIA",
    order: 2,
  },
  {
    name: "Aquaman",
    description: "Asiste un mes completo al agua",
    points: 1,
    type: "GENERAL",
    subtype: "ASISTENCIA",
    order: 3,
  },
  {
    name: "De la casa",
    description: "Completa tu primer trimestre",
    points: 1,
    type: "GENERAL",
    subtype: "ASISTENCIA",
    order: 4,
  },
  {
    name: "Veterano",
    description: "Completa tu primer año",
    points: 1,
    type: "GENERAL",
    subtype: "ASISTENCIA",
    order: 5,
  },
  {
    name: "Old school",
    description: "Completa más de dos años",
    points: 1,
    type: "GENERAL",
    subtype: "ASISTENCIA",
    order: 6,
  },
  {
    name: "Anciano",
    description: "Supera los 9km/h (media)",
    points: 1,
    type: "SUP",
    subtype: "VELOCIDAD",
    order: 1,
  },
  {
    name: "Rookie",
    description: "Supera los 10km/h (media)",
    points: 1,
    type: "SUP",
    subtype: "VELOCIDAD",
    order: 2,
  },
  {
    name: "Ford fiesta",
    description: "Supera los 12km/h (máxima)",
    points: 1,
    type: "SUP",
    subtype: "VELOCIDAD",
    order: 3,
  },
  {
    name: "Ferrari",
    description: "Supera los 14km/h (máxima)",
    points: 1,
    type: "SUP",
    subtype: "VELOCIDAD",
    order: 4,
  },
  {
    name: "Cohete",
    description: "Supera los 16km/h (máxima)",
    points: 1,
    type: "SUP",
    subtype: "VELOCIDAD",
    order: 5,
  },
  {
    name: "Dominguero",
    description: "8 min/km",
    points: 1,
    type: "SUP",
    subtype: "RITMO",
    order: 1,
  },
  {
    name: "Amateur",
    description: "7´30 min/km",
    points: 1,
    type: "SUP",
    subtype: "RITMO",
    order: 2,
  },
  {
    name: "Amateur chetao",
    description: "7 min/km",
    points: 1,
    type: "SUP",
    subtype: "RITMO",
    order: 3,
  },
  {
    name: "Élite 12´6",
    description: "6´45 min/km",
    points: 1,
    type: "SUP",
    subtype: "RITMO",
    order: 4,
  },
  {
    name: "Flat monster",
    description: "6´30 min/km",
    points: 1,
    type: "SUP",
    subtype: "RITMO",
    order: 5,
  },
  {
    name: "Ciclao",
    description: "6´15 min/km",
    points: 1,
    type: "SUP",
    subtype: "RITMO",
    order: 6,
  },
  {
    name: "Élite",
    description: "6 min/km",
    points: 1,
    type: "SUP",
    subtype: "RITMO",
    order: 7,
  },
  {
    name: "Maratoniano",
    description: "Menos de 6 min/km",
    points: 1,
    type: "SUP",
    subtype: "RITMO",
    order: 8,
  },
  {
    name: "Principiante",
    description: "7 min/km",
    points: 1,
    type: "SUP",
    subtype: "DOWNWIND",
    order: 1,
  },
  {
    name: "Respetable",
    description: "6´45 min/km",
    points: 1,
    type: "SUP",
    subtype: "DOWNWIND",
    order: 2,
  },
  {
    name: "Wave rider",
    description: "6´30 min/km",
    points: 1,
    type: "SUP",
    subtype: "DOWNWIND",
    order: 3,
  },
  {
    name: "Rider NSP",
    description: "6´15 min/km",
    points: 1,
    type: "SUP",
    subtype: "DOWNWIND",
    order: 4,
  },
  {
    name: "Molokai",
    description: "6 min/km",
    points: 1,
    type: "SUP",
    subtype: "DOWNWIND",
    order: 5,
  },
  {
    name: "Kai Lenny",
    description: "Menos de 6 min/km",
    points: 1,
    type: "SUP",
    subtype: "DOWNWIND",
    order: 6,
  },
  {
    name: "Abuelita",
    description: "Sprint de 2 min",
    points: 1,
    type: "SUP",
    subtype: "SPRINTS",
    order: 1,
  },
  {
    name: "Benjamin Button",
    description: "Sprint de 1´45 min",
    points: 1,
    type: "SUP",
    subtype: "SPRINTS",
    order: 2,
  },
  {
    name: "Rápido pero no mucho",
    description: "Sprint de 1´30 min",
    points: 1,
    type: "SUP",
    subtype: "SPRINTS",
    order: 3,
  },
  {
    name: "Rápido",
    description: "Sprint de 1´15 min",
    points: 1,
    type: "SUP",
    subtype: "SPRINTS",
    order: 4,
  },
  {
    name: "Sprinter nato",
    description: "Sprint de 1´05 min",
    points: 1,
    type: "SUP",
    subtype: "SPRINTS",
    order: 5,
  },
  {
    name: "Power machine",
    description: "Sprint de 1 min",
    points: 1,
    type: "SUP",
    subtype: "SPRINTS",
    order: 6,
  },
  {
    name: "Súper sónico",
    description: "Sprint por debajo de 1 min",
    points: 1,
    type: "SUP",
    subtype: "SPRINTS",
    order: 7,
  },
  {
    name: "Gondolero",
    description: "Completa 1 medalla de cada disciplina de SUP",
    points: 1,
    type: "SUP",
    subtype: "COMBINADAS",
    order: 1,
  },
  {
    name: "Surfer respetable",
    description: "Completa 2 medallas de cada disciplina de SUP",
    points: 1,
    type: "SUP",
    subtype: "COMBINADAS",
    order: 2,
  },
  {
    name: "Paddle surfer definitivo",
    description: "Completa 3 medallas de cada disciplina de SUP",
    points: 1,
    type: "SUP",
    subtype: "COMBINADAS",
    order: 3,
  },
  {
    name: "King of the paddle",
    description: "Completa todas medallas de cada disciplina de SUP",
    points: 1,
    type: "SUP",
    subtype: "COMBINADAS",
    order: 4,
  },
  {
    name: "Tortuguita",
    description: "Corre 1km a 6:30",
    points: 1,
    type: "FÍSICO",
    subtype: "VELOCIDAD",
    order: 1,
  },
  {
    name: "Walking dead",
    description: "Corre 1km a 6:15",
    points: 1,
    type: "FÍSICO",
    subtype: "VELOCIDAD",
    order: 2,
  },
  {
    name: "Mini galgo",
    description: "Corre 1km a 6",
    points: 1,
    type: "FÍSICO",
    subtype: "VELOCIDAD",
    order: 3,
  },
  {
    name: "Pequeño Usain",
    description: "Corre 1km a 5:30",
    points: 1,
    type: "FÍSICO",
    subtype: "VELOCIDAD",
    order: 4,
  },
  {
    name: "Flash",
    description: "Corre 1km a 5:00/km o menos",
    points: 1,
    type: "FÍSICO",
    subtype: "VELOCIDAD",
    order: 5,
  },
  {
    name: "De camino al cielo",
    description: "Realiza 1 dominada",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA AÉREA",
    order: 1,
  },
  {
    name: "Thor baja forma",
    description: "Realiza 3 dominadas",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA AÉREA",
    order: 2,
  },
  {
    name: "Duro como una piedra",
    description: "Realiza 5 dominadas estrictas",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA AÉREA",
    order: 3,
  },
  {
    name: "Tiembla Dwayne!",
    description: "Realiza 10 dominadas estrictas",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA AÉREA",
    order: 4,
  },
  {
    name: "La montaña",
    description: "Realiza 15 dominadas estrictas",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA AÉREA",
    order: 5,
  },
  {
    name: "La montaña",
    description: "Realiza 15 dominadas estrictas",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA AÉREA",
    order: 5,
  },
  {
    name: "Proyecto forzudo",
    description: "Realiza 5 flexiones estrictas",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA TERRESTRE",
    order: 1,
  },
  {
    name: "Culturista amateur",
    description: "Realiza 10 flexiones estrictas",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA",
    order: 2,
  },
  {
    name: "Fiera",
    description: "Realiza 15 flexiones estrictas",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA",
    order: 3,
  },
  {
    name: "Strong as hell",
    description: "Realiza 20 flexiones estrictas",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA",
    order: 4,
  },
  {
    name: "Pechos de acero",
    description: "Realiza 30 flexiones estrictas",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA",
    order: 5,
  },
  {
    name: "Panchut",
    description: "Realiza la plancha durante 30 segundos",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA TERRESTRE",
    order: 1,
  },
  {
    name: "Four pack",
    description: "Realiza la plancha durante 60 segundos",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA TERRESTRE",
    order: 2,
  },
  {
    name: "Six pack",
    description: "Realiza la plancha durante 90 segundos",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA TERRESTRE",
    order: 3,
  },
  {
    name: "Mastodonte",
    description: "Realiza la plancha durante 120 segundos",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA TERRESTRE",
    order: 4,
  },
  {
    name: "Acero pa los barcos",
    description: "Realiza la plancha durante más de 150 segundos",
    points: 1,
    type: "FÍSICO",
    subtype: "FUERZA TERRESTRE",
    order: 5,
  },
  {
    name: "Peter la Anguila",
    description: "Completa 1 medalla de cada disciplina de físico",
    points: 1,
    type: "FÍSICO",
    subtype: "COMBINADAS",
    order: 1,
  },
  {
    name: "Máquina bien engrasada",
    description: "Completa 2 medalla de cada disciplina de físico",
    points: 1,
    type: "FÍSICO",
    subtype: "COMBINADAS",
    order: 2,
  },
  {
    name: "John cena",
    description: "Completa 3 medalla de cada disciplina de físico",
    points: 1,
    type: "FÍSICO",
    subtype: "COMBINADAS",
    order: 3,
  },
  {
    name: "Rocky Balboa",
    description: "Completa 4 medalla de cada disciplina de físico",
    points: 1,
    type: "FÍSICO",
    subtype: "COMBINADAS",
    order: 4,
  },
  {
    name: "Hércules",
    description: "Completa todas las medalla de cada disciplina de físico",
    points: 1,
    type: "FÍSICO",
    subtype: "COMBINADAS",
    order: 5,
  },
];

// AMISTAD:

// Antisocial: Haz 1 amigo
// Coleguita: Haz 5 amigos
// Relaciones públicas: Haz 15 amigos
// Rey de la fiesta: Haz 25 amigos
