export const users_DB_DATA = [
  {
    username: "jparken0",
    firstname: "Jarrod",
    lastname: "Parken",
    email: "jparken0@unicef.org",
    dateborn: "2004-09-16",
    role: "STUDENT",
    team: "Rookies",
  },
  {
    username: "sfilgate1",
    firstname: "Spike",
    lastname: "Filgate",
    email: "sfilgate1@ebay.com",
    dateborn: "2008-08-01",
    role: "STUDENT",
    team: "Pro team",
  },
  {
    username: "imorrant2",
    firstname: "Ingram",
    lastname: "Morrant",
    email: "imorrant2@fda.gov",
    dateborn: "2006-02-09",
    role: "STUDENT",
    team: "Pro team",
  },
  {
    username: "ldugald3",
    firstname: "Lotte",
    lastname: "Dugald",
    email: "ldugald3@state.tx.us",
    dateborn: "2003-05-21",
    role: "STUDENT",
    team: "Pro team",
  },
  {
    username: "psumshon4",
    firstname: "Pietro",
    lastname: "Sumshon",
    email: "psumshon4@behance.net",
    dateborn: "2008-06-21",
    role: "STUDENT",
    team: "Pro team",
  },
  {
    username: "alarrie5",
    firstname: "Adore",
    lastname: "Larrie",
    email: "alarrie5@jigsy.com",
    dateborn: "2010-11-30",
    role: "STUDENT",
    team: "Krakens",
  },
  {
    username: "fpena6",
    firstname: "Fonz",
    lastname: "Pena",
    email: "fpena6@google.ca",
    dateborn: "2007-09-19",
    role: "STUDENT",
    team: "Krakens",
  },
  {
    username: "bschild7",
    firstname: "Brit",
    lastname: "Schild",
    email: "bschild7@mail.ru",
    dateborn: "2007-02-10",
    role: "STUDENT",
    team: "Krakens",
  },
  {
    username: "ttowson8",
    firstname: "Tab",
    lastname: "Towson",
    email: "ttowson8@un.org",
    dateborn: "2008-06-30",
    role: "STUDENT",
    team: "Krakens",
  },
  {
    username: "hdockwra9",
    firstname: "Henderson",
    lastname: "Dockwra",
    email: "hdockwra9@livejournal.com",
    dateborn: "2007-06-21",
    role: "STUDENT",
    team: "Krakens",
  },
  {
    username: "lbudgea",
    firstname: "Livvyy",
    lastname: "Budge",
    email: "lbudgea@zimbio.com",
    dateborn: "2007-03-09",
    role: "STUDENT",
    team: "Krakens",
  },
  {
    username: "prickcordb",
    firstname: "Parker",
    lastname: "Rickcord",
    email: "prickcordb@dropbox.com",
    dateborn: "2008-08-30",
    role: "STUDENT",
    team: "Pringaos",
  },
  {
    username: "epriddingc",
    firstname: "Esme",
    lastname: "Pridding",
    email: "epriddingc@tinyurl.com",
    dateborn: "2010-06-14",
    role: "STUDENT",
    team: "Pringaos",
  },
  {
    username: "edaintreed",
    firstname: "Emlynne",
    lastname: "Daintree",
    email: "edaintreed@utexas.edu",
    dateborn: "2010-07-06",
    role: "STUDENT",
    team: "Pringaos",
  },
  {
    username: "askirvene",
    firstname: "Abeu",
    lastname: "Skirven",
    email: "askirvene@unblog.fr",
    dateborn: "2005-03-03",
    role: "STUDENT",
    team: "Pringaos",
  },
  {
    username: "cwhaleyf",
    firstname: "Chadwick",
    lastname: "Whaley",
    email: "cwhaleyf@latimes.com",
    dateborn: "2009-07-13",
    role: "STUDENT",
    team: "Pringaos",
  },
  {
    username: "nscramageg",
    firstname: "Nelli",
    lastname: "Scramage",
    email: "nscramageg@spotify.com",
    dateborn: "2009-04-23",
    role: "STUDENT",
    team: "Pringaos",
  },
  {
    username: "lstopsh",
    firstname: "Laney",
    lastname: "Stops",
    email: "lstopsh@mtv.com",
    dateborn: "2009-01-12",
    role: "STUDENT",
    team: "Rookies",
  },
  {
    username: "lludli",
    firstname: "Ludovico",
    lastname: "Ludl",
    email: "lludli@google.cn",
    dateborn: "2007-12-22",
    role: "STUDENT",
    team: "Rookies",
  },
  {
    username: "mkingj",
    firstname: "Michaella",
    lastname: "King",
    email: "mkingj@newyorker.com",
    dateborn: "2004-11-28",
    role: "STUDENT",
    team: "Rookies",
  },
];
